services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-service
    ports:
      - "5439:5432"

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432/auth-service
    depends_on:
      - postgres

  client-app:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - auth-server
